version: 2
jobs:
  build_and_test:
    working_directory: ~/bongo
    docker:
      - image: circleci/php
    steps:
      # Dependencies
      - checkout
      - restore_cache:
          key: bongo-{{ .Branch }}-{{ checksum "./composer.lock" }}-v1
      - run: composer install --prefer-dist --no-interaction
      - save_cache:
          key: bongo-{{ .Branch }}-{{ checksum "./composer.lock" }}-v1
          paths:
            - '/root/.composer/cache'
            - './vendor'

      # Code style checks
      - run:
          name: Code style checks
          command: |
            vendor/bin/ecs check src

      # Testing
      - run:
          name: Run Unit tests
          command: |
            mkdir -p ~/phpunit
            vendor/bin/phpunit --log-junit ~/phpunit/junit.xml
          when: always
      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: ~/phpunit

workflows:
  version: 2
  tests:
    jobs:
      - build_and_test