version: 2
jobs:
  build_and_test:
    working_directory: ~/bongo
    docker:
      - image: youseeu/docker-php-node
    steps:
      # Installation
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php && \
            php -r "unlink('composer-setup.php');" && \
            chmod +x ./composer.phar && \
            mv ./composer.phar /usr/local/bin/composer

      # Dependencies
      - checkout
      - restore_cache:
          key: bongo-{{ .Branch }}-{{ checksum "./composer.lock" }}-v1
      - run: composer install --prefer-dist --no-interaction
      - save_cache:
          key: bongo-{{ .Branch }}-{{ checksum "./composer.lock" }}-v1
          paths:
            - '/root/.composer/cache'
            - './vendor'

      # Code style checks
      - run:
          name: Code style checks
          command: |
            PHP_CS_FIXER_FUTURE_MODE=1 vendor/bin/php-cs-fixer --config=.php_cs.dist --verbose --diff --dry-run fix

      # static analysis
      - run:
          name: Psalm static analysis
          command: |
            vendor/bin/psalm --show-info=false src tests

      # https://circleci.com/docs/2.0/building-docker-images/#section=configuration
      - setup_remote_docker:
          docker_layer_caching: true

      # Install Docker client
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Phpstan static analysis
          command: |
            docker run --rm -v $PWD:/app phpstan/phpstan analyse /app/src

      # Testing
      - run:
          name: Run Unit tests
          command: |
            mkdir -p ~/phpunit
            vendor/bin/phpunit --log-junit ~/phpunit/junit.xml
          when: always
      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: ~/phpunit

workflows:
  version: 2
  tests:
    jobs:
      - build_and_test